# Site settings
title: OpenHome Labs
email: info@openhomelabs.com
description: > # this means to ignore newlines until "baseurl:"
  OpenHome Labs is the home of the groundbreaking distributed
  audio platform, OpenHome (tm).
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://openhomelabs.com" # the base hostname & protocol for your site
twitter_username: openhome
github_username:  openhome

# Build settings
markdown: kramdown
